trigger: none

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'

steps:
- task: UseDotNet@2
  displayName: Setup Dotnet
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '$(solution)'